- abci/client/grpc_client.go
- go.mod
- go.sum
- privval/grpc/util.go
`insecure` prevents us from using an older grpc version which is necessary for cosmos's custom protobuf generation
> not use insecure

- internal/blocksync/reactor.go
- internal/blocksync/reactor_test.go
- internal/consensus/reactor.go
- internal/consensus/reactor_test.go
- internal/evidence/reactor.go
- internal/evidence/reactor_test.go
- internal/mempool/reactor.go
- internal/mempool/reactor_test.go
- internal/p2p/pex/reactor.go
- internal/p2p/pex/reactor_test.go
- internal/p2p/router.go
- internal/statesync/reactor.go
- internal/statesync/reactor_test.go
- node/node.go
- node/seed.go
- node/setup.go
Previously it's possible for peer connections established without having all descriptors registered. This PR waits synchronously for descriptor registration before proceeding to establish peer connections.
> Fix open connection race condition

- internal/consensus/replay.go
- internal/consensus/state.go
- types/params.go
- Bump block part size to 1MB
- Only fsync if the proposer has received all block parts
> Bump block part size and delay fsync

- config/config.go
- config/toml.go
- internal/mempool/mempool.go
Add a config that allows node to specify the minimum number of transactions needed for mempool to notify consensus state machine about transactions. For example, if this config is set as 10, then the node would not start to propose block unless the minimum threshold is met.
> Add Tx notification threshold

- internal/consensus/state.go
We run into nil pointers if we try to create a block without ensuring that the tx exists in the mempool. We should do a check beforehand.
Ran local docker cluster and sent tx. made sure it worked:
```
tendermint # curl localhost:26657/tx?hash=88D4266FD4E6338D13B845FCF289579D209C897823B9217DA3E161936F031589
{"hash":"88D4266FD4E6338D13B845FCF289579D209C897823B9217DA3E161936F031589","height":"20","index":0,"tx_result":{"events":[{"type":"app","attributes":[{"key":"creator","value":"Cosmoshi Netowoko","index":true},{"key":"key","value":"abcd","index":true},{"key":"index_key","value":"index is working","index":true},{"key":"noindex_key","value":"index is working","index":false}]}]},"tx":"YWJjZA==","proof":{"root_hash":"","data":null,"proof":{"total":"0","index":"0","leaf_hash":null,"aunts":null …
```
> Check for missing tx before block creation

- internal/consensus/state.go
two of the loadtest cluster nodes got stuck as it kept panicking due to a nil proposal block 
```
Nov 18 03:14:53 ip-172-31-36-34 seid[2631731]: 3:14AM INF Replay: Timeout dur=3000 height=676073 module=consensus round=0 step=3
Nov 18 03:14:53 ip-172-31-36-34 seid[2631731]: 3:14AM INF entering prevote step current=676073/0/RoundStepPropose height=676073 module=consensus round=0
Nov 18 03:14:53 ip-172-31-36-34 seid[2631731]: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
Nov 18 03:14:53 ip-172-31-36-34 seid[2631731]:         panic: runtime error: invalid memory address or nil pointer dereference
Nov 18 03:14:53 ip-172-31-36-34 seid[2631731]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1095cf8]
Nov 18 03:14:53 ip-172-31-36-34 …
```
> Vote nil if proposal block is nil

- internal/consensus/state.go
- internal/state/execution.go
At the moment, if a tx is all of the following:
- proposal by tx key is not turned on
- received as part of a block proposal from other peers
- not received via gossip on mempool level
then `CheckTx` won't be run for it, which could cause problems with ante handlers that are CheckTx-only (e.g. min gas config check).
This PR makes it such that for txs from peer proposal that are not already in the local mempool, the validator will run `CheckTx` for them before prevoting the proposed block. Note that `CheckTx` will also insert the tx into the local mempool if the application check passes.
tested with local chain
**will test with multiple nodes with mempool gossiping turned off once merged and released**
> CheckTx for txs from peer proposal

- internal/p2p/peermanager.go
- internal/p2p/pex/reactor.go
- internal/p2p/router.go
The peers fall into an unrecoverable state if they already have a connection to another peer and they try to connect again. 
It seems like Peer A lost its connection to Peer B, but Peer B's mapping was not updated to be aware of this. So when Peer A tries to connect to peer B again, it fails. Therefore if we get a duplicate request where the peer is already connected, we should Error out the existing connection AND return error, this way if it retries it can successfully connect 
```
Dec 12 15:02:02 ip-172-31-33-167 seid[16502]: 3:02PM ERR failed to accept connection err="peer \"4b336938f10433839baf727999e78965dcbae4d5\" is already connected" module=p2p op=incoming/accepted peer=4b336938f10433839baf727999e78965dcbae4d5
Dec 12 15:02:02 ip-172-31-33-167 seid[16502]: 3:02PM INF stopping …
```
> Error if there's dupe connections

- internal/mempool/mempool.go
- internal/mempool/mempool_test.go
Keep track of CheckTx failures per peer with a map + a mutex. The scope of the newly introduce mutex doesn't overlap with any existing mutex so there would be no deadlock. Also exposed a method for objects outside mempool to query CheckTx failures.
unit test
> [0 Gas] add counter for CheckTx failures

- internal/p2p/p2ptest/network.go
- internal/p2p/router.go
- internal/p2p/router_init_test.go
- internal/p2p/router_test.go
- node/setup.go
This PR allows registering a dynamic node ID filterer on the p2p router. The dynamic filterer can be based on mempool CheckTx failure counts.
The stages of  adding a peer look like:
1. the process is notified of a connection request. Nothing about the sender is known at this point.
2. the process "Accept()" the request. At this point the IP of the sender is known.
3. the process "handshake()" the request (not TCP handshake but an application concept). At this point the node ID is known.
4. the process registers the node ID and starts to process its messages.
The filtering in this PR happens between 3 and 4. Alternatively it's also possible to filter (by IP) between 2 and 3. However this requires maintaining a mapping between IP and node ID, which could be an additional bug surface area …
> Add node ID filtering for peers blacklisted due to CheckTx failures

- config/config.go
- config/toml.go
- internal/consensus/common_test.go
- internal/consensus/reactor_test.go
- internal/mempool/mempool.go
- internal/mempool/mempool_test.go
- internal/mempool/types.go
- node/node.go
- node/node_test.go
- node/setup.go
- test/fuzz/tests/mempool_test.go
- Added two new mempool configs: one controls whether blacklisting feature is on and the other indicates the threshold (over which a peer sending too many CheckTx-failing txs will be blacklisted if the former config is on)
- Evict peer if above threshold. Note that TM will retry connection, which would fail because a blacklisted node will not have connection established
unit test
> [0 Gas] evict peer connection if they send too many transactions failing CheckTx

- internal/consensus/state.go
Should check if its nil before using it, other places also do the something
Right now if the proposal is nil, it'll fall behind on consensus error then when you restart, it'll catch up but then fall behind again. This is only possible for non-val nodes as this field will be nil
> move around state checks

- rpc/jsonrpc/client/ws_client.go
This fixes the issue where https addr isn't converted to wss for websocket
found the issue here: https://github.com/sei-protocol/sei-tendermint/blob/46d0a598a7f5c67cbdefea37c8da18df2c25d184/rpc/jsonrpc/client/ws_client.go#L92 
tendermint repo does this fix: https://github.com/tendermint/tendermint/blob/64747b2b184184ecba4f4bffc54ffbcb47cfbcb0/rpc/jsonrpc/client/ws_client.go#L93
> [client] Fix https / wss conversion

- cmd/tendermint/commands/reset.go
- cmd/tendermint/commands/reset_test.go
- cmd/tendermint/main.go
Cherrypick unsafe-reset-all based on https://github.com/tendermint/tendermint/blob/v0.37.0-rc1/cmd/tendermint/commands/reset.go#L16
Note that our tendermint version no longer uses an `AddrBook`, so it's not part of the reset
unit test
> cherrypick unsafe-reset-all

- cmd/tendermint/commands/run_node.go
- config/config.go
- config/toml.go
- internal/p2p/peermanager.go
- internal/p2p/peermanager_test.go
- node/setup.go
Added unconditional peer based on v0.37.0-rc1 implementation, with the following differences:
- config field name is in `-` instead of `_` (if we want to change to `_` we might want to do it for all configs in a separate PR)
- implemented unconditional peer logics in `peermanager` instead of `switch` which was removed in the tendermint version we originally forked from
unit tests
> Cherrypick unconditional peers

- go.mod
- light/client.go
- light/client_benchmark_test.go
- light/client_test.go
- light/detector.go
- light/detector_test.go
- light/example_test.go
- light/light_test.go
This original PR https://github.com/tendermint/tendermint/pull/7781 was introduced in Feb 2022, however it was later reverted and doesn't exist in latest master of open source. 
This change enforce us to use two different RPC DNS name for primary and witness address, which we believe is not necessary at this point given open source has already reverted.
Tested state sync with the fix
> [Bug Fix] Revert PR "Don't allow duplicates for light client providers #7781"

- config/config.go
- internal/statesync/reactor.go
**Problem**:
The current issue is that tendermint enforce backfill until number of blocks reach max_age_num_blocks as well as backfill until 48 hours ago, controlled by max_age_duration. This means to complete the state sync, it will need to spend couple of hours doing backfill, this is not acceptable to fast bootstrap a RPC node.
Although this is configurable now, we do not want to change the genesis configuration in order to change the backfill behavior, because this config is also used in other places for different purposes, e.g. pruning.
**Solution**:
Ideally, we want a separate set of configurations to configure the backfill history for RPC node (Most RPC nodes doesn't need backfill at all)
This PR introduced two new startup configurations:
- backfill-blocks (maximum number of blocks …
> [State Sync] Add backfill configurations for state sync

- go.mod
- go.sum
- internal/p2p/pex/reactor.go
Keep an LRU cache of recently used addresses, so when we run into issues with no more available addresses, we simply retry the recent ones
Ran local integration test for tendermint:
```
~/sei-tendermint | p2p-no-avail  rm -rf build/node* ; make build-linux && make build-docker-localnode && make localnet-start
```
> Keep LRU cache of recent peers and retry if we run out

- internal/state/rollback.go
There are three heights: Block Height (BH), App Height (AH), State Height (SH). Those three are updated in this order so it's possible to have the following combinations:
H = BH = AH = SH
H = BH = AH = SH+1
H = BH = AH + 1 = SH + 1
With --hard, the desired output should be H-1 = BH = AH = SH all three scenarios.
Without --hard, the outputs should be
H = BH, H-1 = AH = SH
H-1 = BH = AH = SH
H-1 = BH = AH = SH
Regardless of whether --hard or not, SH is being rolled back to H-1, so its app hash should always be set as the hash in block H's header
tested on devnet-2
> Fix tendermint state hard rollback logic

- internal/mempool/mempool.go
**Problem:**
Currently in checkTx, if recheck cursor is not nil (means there's some remaining tx haven't finished recheck), it will return an error to the current transaction and will not accept any new transactions, and will not trigger the retry of existing rechecks, not even to remove them from the checklist or evict them when they expires. This logic is problematic, because whenever there's an transaction that failed the recheck, it will block all future transactions and can not self recover any more.
This failure could happen frequently for broadcastTx calls, because cosmos context will branch out the temporary state in the checkTx mode (https://docs.cosmos.network/v0.45/core/context.html#store-branching), this would case the account sequence number queried from the keeper of the …
> Bug Fix: recheck should not cause all future transactions to halt

- internal/p2p/channel.go
- internal/p2p/pqueue.go
- internal/p2p/router.go
- internal/p2p/rqueue.go
- internal/p2p/rqueue_test.go
This PR cherrypicks changes from https://github.com/tendermint/tendermint/pull/8929 which fixes the issue described in https://github.com/tendermint/tendermint/issues/8903
TLDR:
The issue is that the 0.35 priority queue impl uses bounded channels which causes unwanted blocking under certain scenarios. The main difference of the "simple" pqueue is that it added an additional time-based signal that fires every 10ms to make sure things are always moving.
The queue type can be configured under `P2P.queue-type`
unit test & test on load cluster
> Cherrypick p2p priority queue optimizations

- internal/mempool/mempool.go
Seeing a lot of of check Tx logs 
The caller is suppose to have the write lock but it doesn't seem to be true: 
https://github.com/sei-protocol/sei-tendermint/blob/main/internal/mempool/mempool.go#L735
Output the TX hash to see if we're running into race condition issues in the mempool or running into a callback deadlock 
Copied these from oss repo
> Improve recheckTx logs

- internal/p2p/router.go
- internal/p2p/router_test.go
Cherrypick p2p changes to make p2p router more resilient to transient errors
Original PR: https://github.com/tendermint/tendermint/pull/8759
unit test
> Cherrypick https://github.com/tendermint/tendermint/pull/8759

- config/config.go
- internal/consensus/state.go
e.g https://github.com/sei-protocol/sei-cosmos/pull/153
Based on the logs, the data race is between QueryContext and the Finalizeblock for app.checkState.ctx.
I narrowed it cause and it seems like with UnsafeBypassCommitTimeoutOverride=true on by default, the single node consensus is much faster as it doesn't need to wait for timeout, all the datarace failures are happening in the query cli unit tests so i suspect that the queries and the async network are handled in different gorountines and thus have async access to checkState.Ctx (one is updating through finalizeBlock while the unit test is querying it)
Its fine to set to false, since it's mainly exposing the behavior that CLI queries do not have a freshness guarantee, which is expected as the data is constantly changing 
Tag has this …
> [config] set override unsafeTimeoutOverride to false by default

- cmd/tendermint/commands/run_node.go
- cmd/tendermint/main.go
- config/config.go
- config/db.go
- config/toml.go
- internal/p2p/pex/reactor.go
- internal/p2p/router.go
- libs/service/service.go
- node/node.go
- node/node_test.go
- node/public.go
- node/seed.go
- rpc/test/helpers.go
- test/e2e/node/main.go
Add a channel to notify the node class when there are no more peers. When this happens, the node exits
Ran 4 node tendermint cluster where I injected failures, verified that node was shut down.
> Self kill process if there are no available peers

- abci/client/mocks/client.go
- config/config.go
- internal/p2p/pex/reactor_test.go
- internal/state/execution_test.go
- node/node_test.go
Per this comment: https://github.com/sei-protocol/sei-tendermint/pull/50#issuecomment-1411414817
We've done enough testing with multiple clusters, should be fine to set it to default now to reduce operational complexity for genesis
> Default p2p with simple priority

- internal/consensus/state.go
In the open source version of Tendermint, `defaultDoPrevote` always performs `signAddVote` before returning. However, after adding some of the gossip tx logic, we've noticed that nodes will occaisionally hang. The reason is that there are edge cases where we don't end up signing. As a result, consensus gets stuck since all the nodes wait for at least 2/3 voting before proceeding: https://sourcegraph.com/github.com/tendermint/tendermint@35581cf54ec436b8c37fabb43fdaa3f48339a170/-/blob/consensus/state.go?L2123
Ran loadtest cluster overnight:
> Ensure that defaultDoPrevote always signs a vote before returning

- internal/consensus/state.go
We don't need to panic if we're flushing the WAL which fixes unit tests that are failing due to
```
panic: error flushing wal after receiving all block parts error=write: autofile is closed [recovered]
panic: error flushing wal after receiving all block parts error=write: autofile is closed [recovered]
panic: error flushing wal after receiving all block parts error=write: autofile is closed
```
This also mimics OSS behavior https://github.com/sei-protocol/sei-tendermint/actions/runs/4115746669/jobs/7104875975
Unit tests pass
> fix unit test

- internal/p2p/transport_mconn.go
router decides whether to dial a peer or not based on peermanager's state, not directly on whether there is already a tcp connection with the peer or not. Even though peermanager's state is supposed to be updated when the underlying tcp connection is updated or closed, in practice they do go out of sync occasionally. One scenario would be that there is a tcp connection alive but one side (or both)'s peermanager considers the connection to be already closed and will thus decide to dial, but the dialing would fail because of the existing connection. This PR makes sure that before attempting to dial a peer, the underlying TCP connection must have already been closed.
needs to be tested on a test cluster
> Make sure TCP connection is absent before dialing

- internal/mempool/reactor.go
These log messages are pretty noisy, we can set them to debug
> Make some checktx logs debug

- internal/p2p/p2ptest/network.go
- internal/p2p/peermanager.go
- internal/p2p/peermanager_test.go
- internal/p2p/pex/reactor_test.go
- internal/p2p/router.go
- node/setup.go
* Delete the peer if we hit max retries 
* If we can't resolve the address then mark it as a private address and dont broadcast it to other nodes (propagating the failure) 
Unit tests, will spin up a LT cluster with this change too, but I don't think it's too risky internally
> Delete peer on max retry 

- internal/blocksync/reactor.go
Idea of increasing sync timeout is to give the node more time to discover and reconnect to peers. That is to prevent the node from switching to consensus mode due to timeout.
> Increase sync timeout to 3min

- internal/statesync/reactor.go
- internal/statesync/reactor_test.go
- node/node.go
Remove peer if it's not available for state sync and restart if there's no peers available. 
This is to restart the node in the case where doesn't have any good peers 
Tested on a LT node and saw that it restarted (forcefully injected code to have it go down to no peers after a minute)
Local setup still works fine (single node)
> Restart node if no statesync peer is available 

- abci/client/grpc_client.go
- state/store.go
When building sei-chain with the latest sei-tendermint main branch we got
```
go: finding module for package github.com/tendermint/tendermint/state
go: finding module for package google.golang.org/grpc/credentials/insecure
github.com/sei-protocol/sei-chain/app imports
github.com/cosmos/ibc-go/v3/modules/apps/transfer/types tested by
github.com/cosmos/ibc-go/v3/modules/apps/transfer/types.test imports
github.com/tendermint/tendermint/state: module github.com/tendermint/tendermint@latest found (v0.35.9, replaced by github.com/sei-protocol/sei-tendermint@v0.1.178-tonytest), but does not contain package github.com/tendermint/tendermint/state
github.com/sei-protocol/sei-chain/cmd/seid/cmd imports
github.com/cosmos/cosmos-sdk/server imports
github.com/tendermint/tendermint/abci/client imports …
```
> revert breaking changes

- abci/client/grpc_client.go
Due to protobuf <> grpc incompatibility, we need to continue using an older version of grpc in cosmos that doesn't have the new insecure function, see: https://github.com/sei-protocol/sei-cosmos/blob/main/go.mod#L150
Ensure that it builds and runs
> Revert grpc breaking change

- abci/client/grpc_client.go
- internal/consensus/common_test.go
- internal/consensus/invalid_test.go
- internal/consensus/mempool_test.go
- internal/consensus/reactor.go
- internal/consensus/reactor_test.go
- internal/consensus/replay.go
- internal/consensus/replay_file.go
- internal/consensus/replay_test.go
- internal/consensus/state.go
- internal/consensus/state_test.go
- internal/consensus/types/round_state.go
Add a mutex-protected wrapper around RoundState to control concurrent access and replace `consensus.State`'s round state field with this new type
tested with v0.1.178-tonytest-2 on internal cluster with race flag turned on and verified no round state related race conditions in 50000 blocks
> Add SafeRoundState

- crypto/merkle/proof.go
- crypto/merkle/proof_value.go
- crypto/merkle/tree_test.go
Fix for https://blog.verichains.io/p/vsa-2022-100-tendermint-forging-membership-proof?utm_source=substack&utm_campaign=post_embed&utm_medium=web
unit test based on the attack simulation proposed in the blog post
> Patch forging empty merkle tree attack vector

- internal/p2p/conn/connection.go
- internal/p2p/router.go
- internal/p2p/transport_mconn.go
- internal/statesync/reactor.go
- internal/statesync/syncer.go
- node/setup.go
1. Add some more useful logs and remove some noisy and useless logs
2. Tune the timeout config for connecting to bad peers
Tested in RPC nodes
> Minor log tunings to make debugging state sync p2p issue easier

- internal/eventbus/event_bus_test.go
- internal/eventlog/eventlog_test.go
- internal/pubsub/pubsub_test.go
- internal/pubsub/subscription.go
- internal/rpc/core/events.go
- internal/state/store.go
- rpc/client/local/local.go
- rpc/client/rpc_test.go
- rpc/coretypes/responses.go
- rpc/jsonrpc/types/types.go
- types/events.go
IBC replayers (e.g. Hermes) are very particular about expected JSON encoding. This PR makes backward compatibility change so that sei's pubsub works with existing replayers
tested by doing a transfer from local sei to axelar testnet
> Fix pubsub json encoding for IBC

- types/genesis.go
- types/genesis_test.go
- types/node_key.go
- Updates the encoding / decoding from `tmjson` to `encoding/json` for genesis file and node key
- This reverts the changes for those files in https://github.com/sei-protocol/sei-tendermint/pull/98 as we were seeing issues during an upgrade 
- Spun up a local chain
> Update Encoding for Genesis file and node key

- types/params.go
We're bumping it to 100m in sei-devnet-3 and atlantic-2, just updating default here too
> Bump max gas to 100m

- node/node.go
TM 0.35 removes unused pubKey from `node.rpcEnv` and only validator nodes will return `validator_info` in the`/status` tm rpc endpoint. This update, however, breaks many auxiliary packages' interface as they cannot correctly serialize the default `validator_info.address`:
TM 0.34:
```
...
"validator_info":{
"address":"E7996BE5125FBF866A3136F15072F2DAB31094FD",
"pub_key":{
"type":"tendermint/PubKeyEd25519",
"value":"AC4vhXhevEYEFktkNQib6prIoSh6YDeZp7yn0kEqO1o="
},
"voting_power":"0"
}
```
TM 0.35:
```
...
"validator_info":{
"address":"",
"pub_key":null,
"voting_power":"0"
}
```
=> ```ERROR failed to spawn chain runtime: relayer error: RPC error to endpoint http://:26657/: serde parse error: expected 40-character hex string, got "" at line 1 column 1298```
This PR reverts the change and add …
> Add unused prival pubKey back to node info

- internal/consensus/metrics.gen.go
- internal/consensus/metrics.go
- internal/consensus/reactor_test.go
- internal/p2p/p2ptest/network.go
```
/sei-tendermint/internal/consensus/state.go:482 +0x148\n"
2:07PM INF stopping service module=consensus service=baseWAL wal=/Users/brandon/.sei/data/cs.wal/wal
2:07PM INF stopping service module=consensus service=Group wal=/Users/brandon/.sei/data/cs.wal/wal
panic: inconsistent label cardinality: expected 1 label values but got 2 in prometheus.Labels{"chain_id":"sei-chain", "validator_address":"96ACAECB1CCF03E2228D035D92F368D242D57A00"} [recovered]
panic: inconsistent label cardinality: expected 1 label values but got 2 in prometheus.Labels{"chain_id":"sei-chain", "validator_address":"96ACAECB1CCF03E2228D035D92F368D242D57A00"} [recovered]
panic: inconsistent label cardinality: expected 1 label values but got 2 in prometheus.Labels{"chain_id":"sei-chain", …
```
> Add metrics label for missing val power

- internal/consensus/metrics.gen.go
- internal/consensus/metrics.go
- internal/consensus/state.go
- internal/state/execution.go
- internal/state/metrics.gen.go
- internal/state/metrics.go
Add gauge metrics at 4 places:
- between receiving the proposal header and processing the last part of the proposal
- flushing async ABCI requests before application commit
- application commit
- mempool update (include recheck tx) after application commit
> Add more gauges in the consensus flow

- internal/p2p/peermanager.go
- internal/p2p/peermanager_scoring_test.go
- internal/p2p/peermanager_test.go
Persistent cores are now hard codes to be 254, however it makes more sense to also dynamically adjust the score even if the peer is a persistent peer based on it's actual quality.
Unit test covered the case
> Adjust persistent peer scores as needed as well

- config/config.go
- internal/dbsync/reactor.go
It's possible for a valid file to have no data in it, in which case we don't want to discard it. Using whether the height associated with the file is zero is a more reliable check for whether the response is empty
tested on psu-test-4
> [DBSync] allow empty files to be synced

- types/events.go
- types/events_test.go
This adds a helper to parse event data for use with eventstream to make use of parsed eventdata by other applications
Adding unit tests
> Add helper to try unmarshaling eventdata

- internal/dbsync/syncer.go
Use ModePerm when creating application.db
tested in devnet
> change directory permission

- internal/p2p/peermanager.go
Validator reported following error:
```
panic: assignment to entry in nil map
goroutine 968 [running]:
github.com/tendermint/tendermint/internal/p2p.(PeerManager).Add(0xc0002b8000, {{0xc0d0557928, 0x28}, {0xc0d0557920, 0x5}, {0xc0d0557951, 0x1b}, 0x777d, {0x0, 0x0}})
/root/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.2.4/internal/p2p/peermanager.go:435 +0x505
github.com/tendermint/tendermint/internal/p2p/pex.(Reactor).handlePexMessage(0xc002187040, {0x2bb9610, 0xc0005b88c0}, 0xc133f48800, 0x1?)
/root/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.2.4/internal/p2p/pex/reactor.go:303 +0x72b
github.com/tendermint/tendermint/internal/p2p/pex.(Reactor).processPexCh(0xc002187040, {0x2bb9610?, 0xc0005b88c0}, 0xc0027064e0)
/root/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.2. …
```
> Add check for nil peer address map

- internal/blocksync/reactor.go
we should start the go routine for auto restarting after all the syncs are complete and we switch into consensus mode 
patched rpc node with this change and see that it waited until it finished catching up before it started the go routine
```
#######################################################
#######################################################
[self-remediation]
p2p-no-peers-available-window-seconds = 0
statesync-no-peers-available-window-seconds = 0
blocks-behind-threshold = 300
blocks-behind-check-interval = 30
restart-cooldown-seconds = 1800
```
> Auto switch to blocksync should only start in consensus mode

- internal/consensus/common_test.go
- internal/consensus/pbts_test.go
- internal/consensus/reactor_test.go
- internal/consensus/replay_test.go
- internal/consensus/state.go
- internal/consensus/state_test.go
- internal/evidence/pool_test.go
- internal/state/execution.go
- internal/state/execution_test.go
- node/node_test.go
- test/e2e/tests/evidence_test.go
- types/block.go
- types/block_test.go
- types/events.go
This change reverts https://github.com/tendermint/tendermint/pull/7765/files, which removes the nested Evidence layer. 
By adding the `EvidenceData` layer back, /block endpoint will return
```
"evidence":{"evidence":[]}
```
instead of
```
"evidence":[...]
```
- unit tests
- e2e on local node
> Revert block.Evidence to nested block.Evidence.Evidence

- config/config.go
- config/config_test.go
- internal/p2p/router.go
- internal/rpc/core/doc.go
- internal/rpc/core/events.go
- internal/rpc/core/lag_status.go
- internal/rpc/core/routes.go
- light/proxy/routes.go
- light/rpc/client.go
- rpc/client/http/http.go
- rpc/client/interface.go
- rpc/client/local/local.go
- rpc/client/mock/client.go
- rpc/client/mock/status.go
- rpc/coretypes/responses.go
- rpc/jsonrpc/server/http_json_handler.go
- rpc/jsonrpc/server/http_server.go
- rpc/jsonrpc/server/http_uri_handler.go
- rpc/jsonrpc/server/rpc_func.go
- rpc/jsonrpc/server/ws_handler.go
- rpc/jsonrpc/types/types.go
- rpc/openapi/openapi.yaml
**Problem**:
AWS ELB/ALB required health check endpoint to respond a non 200 response to indicate the service is not healthy. This is currently not available for RPC nodes.
**Solution**:
We will add a new endpoint /lag_status, which will respond a 200 OK when lag is below lag-threshold, and will respond with a non 200 status code when lag is above the lag threshold. In that way, we can easily configure ALB to detect the health of an RPC node
> Add new endpoint to expose lag

- internal/p2p/peermanager.go
- internal/p2p/peermanager_test.go
Whens state syncing existing nodes, this is an easy way to get a set of persistent/bootstrap peers to start but for existing nodes their node-id might already be in the RPC provider's info, which prevents it from starting. 
Not a big issue but more useful when we have problems like in 3.0.0 where nodes keep crashing and we need to re-sync
```
curl $STATE_SYNC_RPC/net_info |jq -r '.peers[] | .url' |sed -e 's#mconn://##' > PEERS
PERSISTENT_PEERS=$(paste -s -d ',' PEERS)
```
> Don't need to panic for self peer

- internal/blocksync/pool.go
- internal/consensus/ticker.go
- internal/evidence/reactor.go
- internal/p2p/conn/connection.go
- internal/p2p/pex/reactor.go
- internal/p2p/rqueue.go
Stop ticker to avoid leaks which causes cpu usage to increase
> stop timer before reset

- internal/blocksync/pool.go
- internal/blocksync/reactor.go
Clean up bprequester goroutines after blocksync finishes
atlantic-2 + profiling
> Cancel bprequestor once blocksync finishes

- config/toml.go
- docs/nodes/configuration.md
**Changes**:
backfill-blocks and backfill-duration are two existing configs available, but not yet exposed to the config file. This change is just exposing them to the config.toml file so that we can start using them
Existing test coverage already cover the logic of backfill.
For config validation, we will test that in integration test
> Add backfill-blocks and backfill-duration configuration to config.toml

- internal/consensus/state.go
The node would crash if there is no prevotes info for a previous round
https://linear.app/seilabs/issue/SEI-5251/tendermint-rpc-bug
tested with block sync without round info
> Fix empty prevote latency metrics

- internal/statesync/reactor.go
- internal/statesync/reactor_test.go
- light/client.go
- light/stateprovider.go
- Remove witness when syncer p2p status is down
- Unit test now verifies the witness is removed upon p2p-down
> Remove witness when removing provider for p2p-down

- cmd/tendermint/commands/light.go
- config/config.go
- config/toml.go
- internal/consensus/state.go
- internal/dbsync/reactor.go
- internal/statesync/reactor.go
- light/client.go
- light/client_benchmark_test.go
- light/client_test.go
- light/detector.go
- light/detector_test.go
- light/example_test.go
- light/light_test.go
- light/setup.go
- light/stateprovider.go
- Removes witnesses for "client failed to respond" and "light block not found" errors
- Add a blacklist with recently removed witnesses and set a minimum duration before they can be added back
- `consensusParams` returns after any witness responds vs waiting on all responses
- Tested on a pacific-1 rpc during state sync w/ p2p and reproed
- Added unit tests
> State sync fixes: Remove Bad Witnesses and Don't Wait on All Witnesses for ConsensusParams

- internal/p2p/metrics.gen.go
- internal/p2p/metrics.go
- internal/p2p/p2ptest/network.go
- internal/p2p/peermanager.go
- internal/p2p/peermanager_scoring_test.go
- internal/p2p/peermanager_test.go
- internal/p2p/pex/reactor_test.go
- internal/p2p/router_test.go
- node/node.go
- node/seed.go
- node/setup.go
Add metrics for peer score for ease of debugging
Deployed to autobake:
> Add metrics for peermanager scores

- internal/consensus/state.go
This change will help to reduce the noisy logs such as
> Reduce noisy tendermint logs

- internal/pubsub/query/query.go
- internal/pubsub/query/query_test.go
- internal/pubsub/query/syntax/parser.go
- internal/pubsub/query/syntax/scanner.go
- internal/pubsub/query/syntax/syntax_test.go
- internal/state/indexer/block/kv/kv.go
- internal/state/indexer/block/kv/kv_test.go
- internal/state/indexer/tx/kv/kv.go
- internal/state/indexer/tx/kv/kv_test.go
Add regex syntax so that queries like `tx.topics MATCHES '\[.*,xyz,.*\]'` can be written and executed correctly 
unit tests
> Add regex support to query syntax

- internal/blocksync/pool.go
- internal/blocksync/pool_test.go
- internal/blocksync/reactor.go
- internal/blocksync/reactor_test.go
- internal/consensus/state_test.go
- node/node.go
- test/e2e/node/main.go
Import peermanager scores to blocksync reactor and use that to determine which peers to pick for blocksync. We also don't error out on a mismatch of block height from peer who sent it
- Added unit tests
- Deploy to autobake, stopped a validator and restarted - verified catch up still works
- Tested on standalone rpc in pacific-1
> Use peermanager scores for blocksync peers and don't error out on block mismatch

- cmd/tendermint/commands/reset.go
- internal/rpc/core/events.go
- rpc/client/local/local.go
- rpc/client/rpc_test.go
- rpc/coretypes/responses.go
While working on the subscription endpoint for the EVM RPC in sei-chain, ran into an issue when trying to implement the [eth_subscribe endpoint for newHeads](https://docs.alchemy.com/reference/newheads). Notice how the endpoint should return metadata about an eth block but we are querying tendermint for a tendermint block, so we need to convert the tm block to an eth block. This means we need to unmarshal the tm block to get its contents to encode it by doing something like [this](https://github.com/sei-protocol/sei-chain/blob/11b421deaa9b41e30f60bdc7d073ee4276215d6b/evmrpc/block.go#L81).
For the non-subscription endpoint, we use [Events()](https://github.com/sei-protocol/sei-tendermint/blob/f31c31846c491a8a6574acd093e7a775f55fe6b8/rpc/client/interface.go#L131) to get the event data. The …
> Add event data to result event

- internal/mempool/mempool.go
- internal/mempool/priority_queue.go
Previously ReadMaxTxs is not atomic: the state of the priority queue might be changed between the pop and the reenqueue, which would result in panic in some cases. This PR adds an atomic peek function to solve this.
tested locally
> Make ReadMaxTxs atomic

- .github/workflows/tests.yml
- Makefile
- internal/consensus/mempool_test.go
- internal/consensus/reactor_test.go
- internal/consensus/state_test.go
- internal/eventbus/event_bus.go
**Problem:**
Current cap size is 0 which means every publish is synchronous, this cause a lot of extra wait in the consensus loop which would lead to higher block time
**Solution:**
Set a default buffer size to allow for some buffering, this is proved to reduce latency by 100ms when handling 3000 transactions in a single block 
Tested in loadtest chain.
> Perf: Increase buffer size for pubsub server to boost performance

- abci/client/grpc_client.go
- abci/client/mocks/client.go
- abci/client/socket_client.go
- abci/example/kvstore/kvstore.go
- abci/server/grpc_server.go
- abci/types/application.go
- abci/types/messages.go
- abci/types/mocks/application.go
- abci/types/types.go
- internal/consensus/mempool_test.go
- internal/mempool/mempool.go
- internal/mempool/mempool_test.go
- internal/mempool/tx.go
- internal/proxy/client.go
- internal/rpc/core/mempool.go
- internal/state/helpers_test.go
- rpc/client/mock/abci.go
- test/e2e/app/app.go
Add a new `ResponseCheckTxV2` type that includes two additional fields:
- `IsPendingTransaction` will be set to true by application if application determines the transaction to be pending
- `Checker` will be a non-nil function if `IsPendingTransaction` is true that will be invoked by mempool later to determine whether to promote/discard a pending transaction
Note that this PR does NOT include retention or capacity related safeguard logics; those will be in another PR
integration with local sei
> Support pending transaction in mempool

- internal/mempool/mempool.go
- internal/mempool/tx.go
- internal/rpc/core/mempool.go
> Evm fix unconfirmed tx q

- internal/rpc/core/events.go
- rpc/client/local/local.go
- rpc/client/rpc_test.go
- rpc/coretypes/responses.go
This reverts commit 72bb29caf821ed03900bcd74f4ddb439df85f5f1.
> Revert "Add event data to result event (#165)"

- config/config.go
- internal/blocksync/pool.go
- internal/blocksync/reactor.go
**Problems:**
- When deciding if we already caught up and should switch to consensus, we might only have one peer that is falling behind by a lot, and at that time we should not switch to consensus because maxPeerHeight is not accurate
- Currently Tendermint self remediation will send a restart signal ignoring the restart cooldown time, and cosmos will determine whether it should restart or not based on cooldown time. This lead to Tendermint not able to know whether a restart does actually happen or not. 
Solution:
- When checking if we caught up or not, we should have at least 2 peers. We should also maintain the previous MaxPeerHeight before auto restart so that after restart, if both peers are bad, we will not immediately switch to consensus 
- We move the cooldown validation from …
> Fix block sync auto restart not working as expected

- internal/blocksync/reactor.go
We should include an edge case for genesis where max peer is also 0
> Fix edge case for blocksync

- internal/mempool/mempool.go
- internal/mempool/tx.go
Add TTL logic for pending transactions. Note that one difference is we will also remove expired pending transaction from cache so that they can be submitted again
local sei
> add TTL for pending txs

- internal/consensus/state_test.go
- rpc/jsonrpc/server/http_server.go
This is to fix an issue reported: https://github.com/sei-protocol/sei-chain/issues/1214
Tested on local docker chain
```
root@6b45806c2360:/sei-protocol/sei-chain# curl localhost:26657/lag_status |jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100    60  100    60    0     0   7340      0 --:--:-- --:--:-- --:--:-- 15000
{
"current_height": "663",
"max_peer_height": "991",
"lag": "328"
}
root@6b45806c2360:/sei-protocol/sei-chain# curl localhost:26657/lag_status |jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100    60  100    60    0     0   7483      0 --:--:-- --:--:-- --:--:-- 15000
{
"current_height": "684",
"max_peer_height": …
```
> Standardize lag status response format

- internal/mempool/tx.go
- internal/mempool/tx_test.go
There was a bug in the logic that removes transactions (either accepted or rejected) from the pending tx store. Specifically the old logic made it so that only the last index in the parameters gets removed. This PR fixes that and added more test coverage.
unit tests
> Fix bug when popping pending TXs

- abci/types/types.go
- internal/mempool/mempool.go
- internal/mempool/mempool_test.go
- internal/mempool/priority_queue.go
- internal/mempool/priority_queue_test.go
- internal/mempool/tx.go
- When prioritizing transactions, always consider the lowest nonce as highest priority amongst an account's transactions
- Across addresses use gas priority  
- hardhat with large sets of transactions
- unit tests
> [EVM] Allow multiple txs from same account in a block

- internal/mempool/priority_queue.go
- internal/mempool/priority_queue_test.go
- a direct remove was not pushing the next evm transaction onto the queue
- new unit test
> Fix remove tx should push next tx

- internal/mempool/mempool.go
- internal/mempool/tx.go
- before it was firing on every remove
- now it fires only on expires
- unit tests pass
> [EVM] Fix expire metric to only count for expired txs

- internal/mempool/mempool.go
- internal/mempool/priority_queue.go
- internal/mempool/priority_queue_test.go
- internal/rpc/core/mempool.go
- types/tx.go
- Add duplicate nonce support for priority queue so that it doesn't cause duplicates
- A duplicate nonce is inserted after the first existing one in an account's nonce queue
- Add ForEachTx accessor to add locking to priority index to avoid panic from unconfirmed querying (for transaction hash on pending block)
- Unit test
- It's running on slanders-evm
> [EVM] Fix duplicate evm txs from priority queue

- internal/consensus/mempool_test.go
- internal/mempool/mempool.go
- internal/mempool/priority_queue.go
- internal/mempool/priority_queue_test.go
- internal/mempool/tx.go
- EVM TXs should be sorted by nonce AND timestamp if they are inserted to the mempool 
- Avoid inserting a hash to the mempool if it already exists in mempool
- This can happen with EVM transactions because certain transactions can transition to/from pending and re-arrive
- Baking in lower environment
> [EVM] prevent duplicate txs from getting inserted

- internal/mempool/mempool.go
- logs when a transaction is expired with key information
- local testing of log
> [EVM] Add logging for expiration

- internal/mempool/priority_queue.go
- internal/mempool/priority_queue_test.go
- on read, if nil, it skips the item
- remove stale field heapIndex that can throw nil (no longer used)
- add unit test for nil situation (with nil check on read)
> [EVM] Avoid returning nil transactions on ForEach

- abci/client/grpc_client.go
- abci/client/mocks/client.go
- abci/client/socket_client.go
- abci/example/kvstore/kvstore.go
- abci/server/grpc_server.go
- abci/types/application.go
- abci/types/messages.go
- abci/types/mocks/application.go
- abci/types/types.go
- internal/consensus/mempool_test.go
- internal/consensus/state_test.go
- internal/mempool/mempool.go
- internal/mempool/mempool_test.go
- internal/mempool/metrics.gen.go
- internal/mempool/metrics.go
- internal/mempool/priority_queue.go
- internal/mempool/priority_queue_test.go
- internal/mempool/tx.go
- internal/mempool/tx_test.go
- internal/proxy/client.go
- internal/rpc/core/mempool.go
- internal/state/helpers_test.go
- rpc/client/mock/abci.go
- rpc/jsonrpc/server/http_server.go
- test/e2e/app/app.go
- types/tx.go
> [EVM] Rebase main

- internal/consensus/reactor_test.go
- internal/rpc/core/mempool.go
**Problem:**
Current Tendermint is not passing log into the broadcast result, this would cause some information missing when trying to debug broadcast failures.
> Broadcast result should also pass log

- config/config.go
- config/toml.go
- internal/mempool/mempool.go
- types/mempool.go
Manage limits for active txs and pending txs separately
> separate limit for pending tx

- config/toml.go
- internal/mempool/mempool.go
- internal/mempool/mempool_test.go
- internal/mempool/priority_queue.go
- internal/mempool/priority_queue_test.go
- internal/mempool/tx.go
- internal/mempool/tx_test.go
- When an EVM transaction is removed from mempool for any reason other than it being successfully processed and committed (e.g. evicted or expired), we want to move all the transactions after it in the queue back to pending.
- When an EVM transaction is removed from mempool because it's successfully processed, we will only remove itself from the pq without doing anything to the rest of the queue.
unit tests
> Add EVM txs eviction logic

- internal/consensus/reactor.go
- internal/consensus/reactor_test.go
- node/node.go
The debug log in `pickSendVote` accesses peer state in a manner that's subject to race condition, which may lead to page fault when debug is on. This PR changes the access to be via `ToJSON` which is guarded by a mutext. Since `ToJSON` is rather expensive, we only do that if log level is debug.
unit test
> Fix debug log

- internal/mempool/mempool.go
- internal/mempool/mempool_test.go
On sei-js side, when transaction broadcast fails, up until recently we were observing error like the following
```
BroadcastTxError: Broadcasting transaction failed with code 10 (codespace: sdk). Log:
at SigningStargateClient.broadcastTx (/Users/bryantran/code/sei/nft/script/node_modules/@cosmjs/stargate/build/stargateclient.js:267:35)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async main (file:///Users/bryantran/code/sei/nft/script/evm/test.js:17:18) {
code: 10,
codespace: 'sdk',
log: ''
}
```
With recent change https://github.com/sei-protocol/sei-tendermint/pull/201, the log looks like.
```
log: '[{"log":"insufficient fees; got: 1200usei required: 12000usei: insufficient fee"}]'
```
We would like to tweak formatting a bit (from json, to a simple …
> reformat RPC logs for transaction broadcast failure case for easier debugging in frontend

- internal/mempool/mempool.go
- internal/mempool/mempool_test.go
ReapMaxBytesMaxGas and ReapMaxTxs funcs in TxPriorityQueue claim
> Transactions returned are not removed from the mempool transaction store or indexes.
However, they use a priority queue to accomplish the claim
> Transaction are retrieved in priority order.
This is accomplished by popping all items out of the whole heap, and then pushing then back in sequentially. A copy of the heap cannot be obtained otherwise. Both of the mentioned functions use a read-lock (RLock) when doing this. This results in a potential scenario where multiple executions of the ReapMax can be started in parallel, and both would be popping items out of the priority queue.
In practice, this can be abused by executing the `unconfirmed_txs` RPC call repeatedly. Based on our observations, running it multiple times per …
> Use write-lock in (*TxPriorityQueue).ReapMax funcs

- cmd/tendermint/commands/reindex_event.go
- config/config.go
Problem:
- Tendermint command failed to parse the data directory correctly
- home flag is not working properly
This PR add a default home dir and also force to parse the home flag for reindex event to replace the root dir, otherwise it will be empty.
Tested locally for verification
> Fix root dir for tendermint reindex event command

- internal/consensus/replay.go
- internal/state/execution.go
**Problem:**
This is an edge case, a node shutting down process can be triggered during ApplyBlock, and within ApplyBlock function, there are a few major steps:
1. FinalizeBlock
2. SaveFinalizeBlockResponses
3. blockExec.Commit
4. blockExec.store.Save
5. fireEvents -> eventbus service -> subscriber -> index tx events
The process can go down during any of these 5 steps, and if process went down between step 4 and 5, it would lead to the events not fired and txs not being indexed correctly, even though the blocks are successfully commited. After the node restart, when we replay blocks, we will not replay or re-fire those events because there's no block left to be replayed.
**Solution:**
It is a bit hard to make sure events always fire correctly during shutdown, because events publish is an …
> Replay events during restart to avoid tx missing

- internal/mempool/mempool.go
- internal/mempool/mempool_test.go
- internal/mempool/priority_queue.go
- uses heapIndex 
- has safety check to try to mitigate that rare nil panic 
- includes locking adjustment from https://github.com/sei-protocol/sei-tendermint/pull/209
- load testing
- unit tests
> Add heapIndex with safety check

- internal/mempool/tx.go
- internal/mempool/tx_test.go
- Updates Pending Txs insert condition to reject txs when `either` condition is met: max txs # is exceeded OR max bytes after adding in tx is exceeded
- Previously only rejected when both were true
- Added unit tests
- Testing on node
> Pending Txs Update Insert Condition

- internal/consensus/state.go
> More Preccomit logs

- cmd/tendermint/commands/reindex_event.go
- config/config.go
- internal/consensus/replay.go
- internal/mempool/mempool.go
- internal/mempool/mempool_test.go
- internal/state/execution.go
- merge in changes from main 
- unit / load
> [seiv2] Merge main

- internal/mempool/mempool.go
- internal/mempool/metrics.gen.go
- internal/mempool/metrics.go
This PR added two new metrics for tendermint mempool, which tracks number of txs inserted and removed from mempool
> Add metrics for mempool size changes

- rpc/jsonrpc/server/http_json_handler.go
- rpc/jsonrpc/server/http_json_handler_test.go
We should limit the request of json rpc calls
- unit tests
- tested on remote node
> Add request length check to json rpcs

- internal/consensus/metrics.gen.go
- internal/consensus/metrics.go
- internal/state/metrics.gen.go
- internal/state/metrics.go
This PR fix an existing issue caused by previous commits after we added new metrics. Since we don't use labeling, we shouldn't add label to the metric definition.
> Fix metrics labeling issue

- internal/mempool/mempool.go
- internal/mempool/priority_queue.go
- internal/mempool/priority_queue_test.go
- internal/mempool/reactor_test.go
- duplicate nonces cannot coexist in the queue now  (insert is now like an upsert)
- inserts to priority queue will now attempt replacement
- only update stats if the new transaction was inserted
- early bail if already in mempool (moved from insert logic out)
- unit tests
- lower env testing
> [EVM] Adjust locking for replacement

- internal/mempool/mempool.go
- internal/mempool/mempool_test.go
When PendingTxs is full, canAddPendingTx fails [here](https://github.com/sei-protocol/sei-tendermint/blob/f4e9c14ffb9b10cbd3f2cd0c5b34df8f1882426f/internal/mempool/mempool.go#L338), and the [removeHandler](https://github.com/sei-protocol/sei-tendermint/blob/f4e9c14ffb9b10cbd3f2cd0c5b34df8f1882426f/internal/mempool/mempool.go#L301-L308) doesn’t execute. This behavior prevent the addition of identical transactions, as an tx already exists in cache error occurs [here](https://github.com/sei-protocol/sei-tendermint/blob/f4e9c14ffb9b10cbd3f2cd0c5b34df8f1882426f/internal/mempool/mempool.go#L292-L295).
Added unit test coverage
> Remove tx from cache when canAddPendingTx fails

- internal/mempool/mempool.go
- internal/mempool/tx.go
- internal/mempool/tx_test.go
- if a tx has been removed from the hashedTxs, then we need to consider its state to answer `is removed` 
- validating in atlantic-2
> [EVM] check removed including wrapped tx state

- config/config.go
- config/toml.go
- internal/rpc/core/env.go
Add a `TimeoutRead` config for RPC endpoints (read-only)
> Make RPC timeout configurable

- internal/mempool/mempool.go
- internal/mempool/metrics.gen.go
- internal/mempool/metrics.go
The current problem is that we are blind about what's the daily mempool total txs size in bytes, and we are not sure what would be a safe config value to set to limit the size of txs in mempool.
This PR address this concern by adding visibility to monitor total txs size in bytes in mempool.
> Add metrics for total txs bytes in mempool

- internal/pubsub/query/syntax/scanner.go
- internal/pubsub/query/syntax/syntax_test.go
Some contracts define there event topic with `-` which is currently not queryable. This PR allows such keys to be queried.
local sei
> Allow `-` in event query

- config/config.go
- config/toml.go
- internal/blocksync/pool.go
- internal/blocksync/reactor.go
- internal/p2p/peermanager.go
- node/setup.go
This PR speed up block sync and fix a few issues:
1. The bpr pending request number is too high, leading to overuse of network and possible gaps
2. The peer pickup logic is not great, so that it would have a high chance to pick a slow peer or not responding peer, leading to constant timeout
3. We should never switch to consensus mode if we are behind, we should stick to the catch up mode
> Add a new config to speed up block sync

- internal/p2p/peermanager.go
> feat: Exclude unconditional peers when connection limit checking

- internal/blocksync/pool.go
- internal/p2p/peermanager.go
- node/node.go
Sometimes a peer could end up having multiple different IP addresses in the network, some IP are stale, this will cause dial always fail and got stuck. Currently the dial and handshake timeout is not passed in correctly, leading to the fact that the timeout is infinite. So we should enable dial timeout to fix this issue.
> Fix handshake and dial timeout

- cmd/tendermint/commands/rollback.go
- internal/state/rollback.go
- internal/state/rollback_test.go
- internal/state/store.go
Problem:
Currently there's a bug in rollback logic, where after rollback, the node could sometimes run into this error:
```
Dec 04 15:54:59 ip-172-31-26-246 seid[234375]: panic: failed to load validator set at height 118546578: couldn't find validators at height 118546577 (height 118546578 was originally requested): %!w(<nil>)
Dec 04 15:54:59 ip-172-31-26-246 seid[234375]: goroutine 967 [running]:
Dec 04 15:54:59 ip-172-31-26-246 seid[234375]: github.com/tendermint/tendermint/internal/state.buildLastCommitInfo(0xc0683e21c0, {0x3824a58?, 0xc01f8f2ff0?}, 0x11?)
Dec 04 15:54:59 ip-172-31-26-246 seid[234375]:         /root/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.4.3/internal/state/execution.go:500 +0x44e
Dec 04 15:54:59 ip-172-31-26-246 seid[234375]: …
```
> Rollback should not cause missing validatorset

- export/export.go
- node/node.go
- node/node_test.go
in-place testnet needs to modify certain tendermint states in order to fork. This PR exposes the necessary functions.
integration with sei-cosmos
> Export methods for in-place-testnet command

- types/block.go
- utils/slice.go
Add helper function to turn a `types.Block` into an `abci.RequestBeginBlock`
unit test
> Add utils to get RequestBeginBlock

- internal/state/indexer/tx/kv/kv.go
For some unknown reason (still needs investigation) empty bytes can be returned from tx kv store. This would cause a nil pointer panic when returning for tx search endpoints.
tested on archive node
> Exclude nil tx from tx search results

- internal/consensus/replay_stubs.go
- internal/consensus/state.go
- internal/mempool/mempool.go
- internal/mempool/mocks/mempool.go
- internal/mempool/types.go
- internal/state/execution.go
- internal/state/execution_test.go
Previously it's possible for txs in mempool to be evicted during the window between missing txs check and txs retrieval. This PR makes missing txs check and txs retrieval happening under the same mutex section.
no functional change. existing unit test
> Make missing txs check atomic

- internal/consensus/state.go
This is a patch to https://github.com/sei-protocol/sei-tendermint/pull/269 which made missing txs check atomic with tx retrieval but didn't use the atomically retrieved txs to make blocks.
unit test
> Use txs from SafeGetTxsByKeys

- config/config.go
- config/toml.go
- internal/p2p/peermanager.go
- scripts/confix/testdata/v33-config.toml
- scripts/confix/testdata/v34-config.toml
- scripts/confix/testdata/v35-config.toml
Clarifies behavior of config parameter, referenced in multiple locations.
> Fix description of 'unconditional peer' behavior

- internal/consensus/metrics.gen.go
- internal/consensus/metrics.go
- internal/consensus/state.go
Add cumulative metrics for latency and count for each step within a height
> Add step specific metrics

- internal/consensus/mempool_test.go
- internal/consensus/replay_stubs.go
- internal/mempool/mempool.go
- internal/mempool/mempool_test.go
- internal/mempool/mocks/mempool.go
- internal/mempool/types.go
- internal/state/execution.go
- types/params.go
We will rely on EVM tx simulation for estimated gas used as well as the hard block gas limit. If we want to use MinTxsPerBlock, we also need to account for it in `checkTotalBlockGas`. 
existing tests
> Deprecate MinTxsPerBlock

- scripts/metricsgen/metricsgen_test.go
Use `t.TempDir` for creating temporary directories in tests instead of `os`.
> Use testing temp dir in tests

- types/part_set.go
- types/part_set_test.go
Add checks to assert that a non-existing PartSet is considered to be incomplete.
> Consider non-existing PartSet as incomplete

- internal/mempool/reactor.go
- proto/tendermint/mempool/txs.go
- proto/tendermint/mempool/txs_test.go
there is currently no use case for multiple txs in a single envelope, and allowing that might expose us to unwanted effects. Eventually we should change the proto definition from a list to a single item
unit test
> only allow 1 tx per envelope
