- abci/example/example_test.go
- privval/grpc/client_test.go
> Fix insecure dependencies in tests

- internal/consensus/common_test.go
- internal/consensus/state.go
- internal/consensus/state_test.go
Set relationship correctly and add additional labels for entry
> Enrich tracing info

- FORKED_CHANGELOG.md
Create FORKED_CHANGELOG containing changes made on forked project
> Add forked changelog

- config/toml.go
- types/params.go
Overriding default config with the optimization changes we made in loadtest clusters 
Created local chain:
> Update default configs

- config/config.go
- internal/consensus/mempool_test.go
Since we uncommented the fields they need to be populated too
> Set default for TM params

- node/node.go
Handshake is the process of initializing the chain and replaying any blocks needed. It calls InitChain, which updates application state (with genesis state) in memory without committing. Normally those in-mem states would be committed as part of the first replayed block. However in the case of statesync, there will not be block replaying until the statesync chunks are applied, but since applying chunks would mutate application state, this would be mixed up with the previous InitChain state changes, which would cause unwanted effects.
tested with statesync on testnet
> Not InitChain if there is statesync

- internal/mempool/reactor.go
> Make checktx failure info

- go.mod
- go.sum
- internal/p2p/pex/reactor.go
This reverts commit 04d1669cd06120763a2b6b74bf75c9b09de1efb7.
> Revert "Keep LRU cache of recent peers and retry if we run out (#45)"

- internal/p2p/router.go
- internal/p2p/transport_mconn.go
Add logs when transport has error
> Add p2p error logs

- internal/consensus/state.go
When a validator receives a proposal block, they may receive the same transaction in the proposal block that already exists in their mempool. As a result, checkTx will fail and they will end up prevoting nil since. This is exacerbated by the fact that in every block, all validators will send in an oracle vote, so it's possible that each node already has every other node's oracle vote before they receive the proposal block. Remove this check so that the validator can vote for a valid hash.
Deployed in load test cluster.
> Do not re-run checkTx when proposal block is received

- config/toml.go
> Comment out unsafe-commit-timeout-override

- internal/p2p/conn/connection.go
- internal/p2p/pex/reactor.go
- internal/p2p/router.go
Added some new error logs as well as turning some debug logs to error logs
n/a
> More p2p logs

- internal/consensus/state.go
Recreates @codchen PR https://github.com/sei-protocol/sei-tendermint/pull/67/commits/3a5ee0cdb5484d1d38139fbea4afa42d495917cf on a fresh branch to fix issues where a node "hangs". The hanging is due to the fact that it doesn't gossip state updates to peers, and therefore no longer receives consensus updates from its peers.
Ran on clusters for 24h, no more node hang
> Add heartbeater to consensus to prevent node hang

- internal/p2p/transport_mconn.go
This reverts commit 7b77d35e5f6303aa597c23345860fbbab7bcc66f.
This caused no available peers error. Reverting it fixes it. More context:
```
1. node A dials node B
2. node B tries to dial node A and drops the connection
3. node A and B tries to handshake but the connection is gone
iirc we made that change as an attempt to fix the previous p2p issue, but since that's probably fixed by the heartbeater anyway, maybe we can remove it?
dialPeers and acceptPeers are goroutines in router that are not mutually exclusive. Maybe in the future we can consider making dial/accept mutually exclusive for the same peer? just to make things easier to reason with nvm seems impossible with acceptPeers since we don't know the peer ID before connection is established, but for now I think we can just revert …
```
> Revert "Make sure TCP connection is absent before dialing (#66)"

- internal/p2p/peermanager.go
- internal/rpc/core/env.go
- internal/rpc/core/net.go
- rpc/coretypes/responses.go
(cherry picked from commit 64ee99b39d337893768d4646a034bdad896bd3a2)
> Enrich net-info endpoint

- internal/p2p/pex/reactor.go
no available peer logs can be really noisy but at the same time can behelpful with debugging. In the case for no available peers we should just back off on the retries or else it'll be really noisy 
Tested locally:
> backoff on retries when no available peers

- internal/consensus/mempool_test.go
- internal/consensus/reactor.go
- internal/mempool/mempool.go
- types/params.go
Turn off more logs that might be noisy and turn off re-check
> Reduce logs and turn of recheck

- internal/mempool/reactor.go
> Turn off val not in active set checktx logs

- internal/consensus/state.go
- internal/mempool/reactor.go
> Less logs part 2

- internal/consensus/reactor.go
- internal/consensus/state.go
Read by goroutine 1201:
github.com/tendermint/tendermint/internal/consensus.(*Reactor).gossipVotesRoutine()
/root/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.1.177/internal/consensus/reactor.go:784
Write by goroutine 914:
github.com/tendermint/tendermint/internal/consensus.(*State).updateToState()
/root/go/pkg/mod/github.com/sei-protocol/sei-tendermint@v0.1.177/internal/consensus/state.go:876
> Fix race condition around consensus state

- rpc/jsonrpc/client/http_json_client_test.go
- types/vote.go
- types/vote_test.go
Easier to decode the validator with the full address 
https://github.com/sei-protocol/sei-cosmos/pull/194
> Print the whole validator address

- crypto/doc.go
- internal/consensus/state.go
> remove redundant span close

- internal/statesync/syncer.go
- types/params.go
> Default max gas param

- types/events.go
IBC relayer expects certain json tags. Changing `XX_legacy` to `XX` and `XX` to `XX_new` 
local chain
> Fix JSON tag

- node/node.go
- node/node_test.go
- node/public.go
- node/seed.go
The impl was missing a bunch of accessors and variables, just had to add it in 
Node started as seed node:
Restarted node with just the seed node as the bootstrap peer:
Height moving:
Node has 56 peers:
> Fix SeedNode code path

- .github/workflows/tests.yml
- Makefile
- internal/consensus/reactor_test.go
- internal/p2p/p2ptest/network.go
- internal/p2p/peermanager.go
- internal/p2p/peermanager_scoring_test.go
- internal/p2p/peermanager_test.go
- internal/p2p/pex/reactor_test.go
- internal/p2p/router.go
- internal/p2p/router_test.go
- internal/p2p/transport_mconn.go
- internal/statesync/reactor.go
- internal/statesync/syncer.go
- light/client.go
- node/node.go
- node/seed.go
- node/setup.go
**Problem Statement:**
1. State sync requires to have at least 2 valid snapshot peers to start with
2. The default peer dialing order is Unconditional peers (score 255) -> Persistent peers (254)-> other peers order by score (0)
3. If there is a bad peer which pass dial, however always fail to receive message, tendermint will disconnect with that peer, and it will still be the next peer to dial in the loop (since we would never update the score or change the ordering of dial)
**Solution:**
1. We fixed the scoring system for peers by introducing a default score (10) instead of 0, and we will decrease the score for peers that frequently disconnected or dial failed
2. We fixed the cache logic so that each time score is updated, we will invalidate the cache and the ordering will always …
> [Bug Fix] Fix state sync stuck in infinite loop discovering the next bad peer

- internal/consensus/common_test.go
- internal/consensus/pbts_test.go
- internal/consensus/reactor_test.go
- internal/consensus/replay_test.go
- internal/consensus/state.go
- internal/consensus/state_test.go
- internal/evidence/pool_test.go
- internal/state/execution.go
- internal/state/execution_test.go
- node/node_test.go
- test/e2e/tests/evidence_test.go
- types/block.go
- types/block_test.go
- types/events.go
This reverts commit 3558d87e5b722f0f932ca32dbd255caf2d9dd262.
> Revert "Revert block Evidence data type to nested Evidence (#136)"

- libs/rand/random.go
> [Certik Audit] Remove duplicate grand.init

- .github/workflows/tests.yml
- codecov.yml
> Fix codecov

- FORKED_CHANGELOG.md
- internal/consensus/reactor.go
Applying similar changes here 
https://github.com/cometbft/cometbft/pull/241/files
I'll test with a loadtest cluster with all the changes in
> Add Sleep to avoid retrying too quickly

- internal/consensus/state.go
Ensure that we only increment gossip tx key metric once proposals are finalized
Patched sei-node-0 and verified:
> Fix tx key dissemination metric to only emit on complete proposal

- internal/p2p/peermanager.go
We should report metric on Ranked() otherwise it is only updated on Advertise() (and can become stale). For example, if there's a DialFailed() we won't update the metric
> Report metrics on ranked

- internal/mempool/mempool.go
- internal/mempool/tx.go
- internal/rpc/core/mempool.go
> fix unconfirmed tx to consider pending txs

- internal/mempool/mempool.go
- ensure callback is called for mempool
- lower env testing
> Call callback from mempool

- internal/consensus/metrics.gen.go
- internal/consensus/metrics.go
- internal/consensus/state.go
- internal/state/execution.go
- internal/state/metrics.gen.go
- internal/state/metrics.go
This PR add a few more metrics to monitor the finalize block latency breakdown
> Add metrics for block processing latency

- internal/consensus/metrics.gen.go
- internal/consensus/metrics.go
- internal/state/metrics.gen.go
- internal/state/metrics.go
This PR fix an existing issue caused by previous commits after we added new metrics. Since we don't use labeling, we shouldn't add label to the metric definition.
> Fix metrics labeling issue

- node/node.go
> Revert setting timeout

- types/params.go
> Set 10 as default MinTxsInBlock

- .github/workflows/tests.yml
> Update upload-artifact gh action to v4

- internal/p2p/peermanager.go
- fix peer manager goroutine crash when getting non-existing peer node
> fix: peer manager nil pointer

- types/block.go
Previously the slice may contain empty votes if there are fewer validators than last commit
patched on node
> Fix ToReqBeginBlock

- internal/blocksync/pool.go
This PR fix the memory/goroutine leak issue during block sync catch up.
> Fix goroutine leak during block sync

- internal/state/indexer/indexer_service_test.go
- internal/state/indexer/sink/psql/psql_test.go
- types/tx.go
for some reason, the dockertest on `main` branch is failing. This PR fixes that.
existing tests.
> Fix dockertest unit test

- go.mod
- go.sum
- node/node.go
> Add godeltapprof to sei-tendermint to serve additional profiling data

- internal/consensus/memory_limit_test.go
- internal/consensus/peer_state.go
- internal/consensus/peer_state_test.go
- internal/consensus/reactor.go
- internal/consensus/reactor_test.go
- internal/consensus/state.go
- internal/consensus/state_test.go
- libs/bits/bit_array.go
- libs/bits/bit_array_test.go
- types/params.go
- types/part_set.go
- types/part_set_test.go
> fix: prevent excessive Total values

- internal/mempool/cache.go
- internal/mempool/cache_test.go
- internal/mempool/mempool.go
This PR fix the logic for max size, as well as fix a lint issue for select.
Added unit test to verify
> Fix duplicate tx cache max size
